---
title: "Severe cost burden by neighborhood, tenure"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r}
library(acsprofiles)
library(tidyverse)
```

Getting 2015 data from these two ACS tables

```{r}
year <- 2015
bg_table_nums <- list(
  mortgage = "B25091",
  rent = "B25074"
)
```

Have to do some tricky stuff with a couple neighborhoods which are split between block groups. `rbind` everything across geographies.

```{r}
fetch_nh <- bg_table_nums %>%
  map(~{
    acs <- acs.fetch(geography = geo.make(state = 09, county = 09, county.subdivision = "New Haven"),
                     endyear = year, table.number = ., col.names = "pretty")
    geography(acs)$NAME <- "New Haven"
    return(acs)
  })
fetch_gnh <- bg_table_nums %>%
  map(~regional_table(regions$`Greater New Haven`, name = "Greater New Haven", town_lookup = get_town_names(), table.number = ., year = year))
fetch_ct <- bg_table_nums %>%
  map(~acs.fetch(geography = geo.make(state = 09), endyear = year, table.number = ., col.names = "pretty"))
fetch <- bg_table_nums %>% 
  map(~neighborhood_table(., year = year, neighborhood_list = nhv_neighborhoods, blocks = T)) %>% 
  map(function(f) {
    downtown_comb <- f["downtown"] + 0.5 * f["dt50_er50"] + 0.41 * f["dt41_er59"]
    east_rock_comb <- f["east_rock"] + 0.5 * f["dt50_er50"] + 0.59 * f["dt41_er59"] +
      0.51 * f["er51_fh49"] + 0.29 * f["er29_fh71"]
    fair_haven_comb <- f["fair_haven"] + 0.49 * f["er51_fh49"] + 0.71 * f["er29_fh71"]
    acs.colnames(downtown_comb) <- acs.colnames(east_rock_comb) <- acs.colnames(fair_haven_comb) <- acs.colnames(f)
    names <- list("downtown_comb", "east_rock_comb", "fair_haven_comb")
    new_geos <- list(downtown_comb, east_rock_comb, fair_haven_comb) %>%
      map2(names, ~{
        geography(.x)$NAME <- .y
        return(.x)
      })
    #f["dt50_er50"] <- f["dt41_er59"] <- f["er51_fh49"] <- f["er29_fh71"] <- NULL
    
    f <- f %>% append(new_geos) %>% reduce(rbind.acs)
  }) %>%
  map2(fetch_nh, ~rbind.acs(.x, .y)) %>%
  map2(fetch_gnh, ~rbind.acs(.x, .y)) %>%
  map2(fetch_ct, ~rbind.acs(.x, .y))

tables <- vector("list", length = length(bg_table_nums)) %>% setNames(names(fetch))
```

```{r}
# HOUSING COST BURDEN -- MORTGAGE + RENT
# Need: owned units; owned with 30% or more, owned with 50% or more;
# rented units; rented with 30% or more, rented with 50% or more
# both rented & owned
mortgage <- fetch$mortgage
own_costs <- list(
  cost30 = c(8:11, 19:22),
  cost50 = c(11, 22)
)
tables$mortgage <- list(mortgage[, 1], calc_acs_table(own_costs, mortgage[, 1], mortgage)) %>%
  reduce(cbind.acs)
acs.colnames(tables$mortgage) <- c("num_owned_units", "num_owned_cost30", "per_owned_cost30",
                                   "num_owned_cost50", "per_owned_cost50")

rent <- fetch$rent
rent_costs <- list(
  cost30 = c(6:9, 15:18, 24:27, 33:36, 42:45, 51:54, 60:63),
  cost50 = c(9, 18, 27, 36, 45, 54, 63)
)
tables$rent <- list(rent[, 1], calc_acs_table(rent_costs, rent[, 1], rent)) %>%
  reduce(cbind.acs)
acs.colnames(tables$rent) <- c("num_rented_units", "num_rented_cost30", "per_rented_cost30",
  "num_rented_cost50", "per_rented_cost50")

# add another item to tables to hold all_units 
all_units <- tables$mortgage[, 1] + tables$rent[, 1]
cost30 <- tables$mortgage[, 2] + tables$rent[, 2]
cost50 <- tables$mortgage[, 4] + tables$rent[, 4]
tables$cost <- list(all_units,
                    cost30, divide.acs(cost30, all_units, method = "ratio"),
                    cost50, divide.acs(cost50, all_units, method = "ratio")) %>%
  reduce(cbind.acs)
acs.colnames(tables$cost) <- c("num_units", "num_units_cost30", "per_units_cost30", 
                               "num_units_cost50", "per_units_cost50")
rm(mortgage, own_costs, rent, rent_costs, all_units, cost30, cost50)
```

```{r}
all_tables <- tables %>% reduce(cbind.acs)

prof_df <- data.frame(name = all_tables@geography$NAME, all_tables@estimate,
                      row.names = NULL, stringsAsFactors = F) %>%
  tbl_df() %>%
  mutate_at(vars(starts_with("per")), funs(round(., digits = 3))) %>%
  mutate_at(vars(starts_with("num")), funs(round(., digits = 0))) %>%
  filter(!name %in% c("dt50_er50", "dt41_er59", "er51_fh49", "er29_fh71",
                      "downtown", "fair_haven", "east_rock")) %>%
  mutate(name = str_replace_all(name, "_comb", "")) %>%
  arrange(name) %>%
  slice(c(1:3, 5:12, 14, 16:22, 15, 13, 4)) %>%
  mutate(name = str_replace_all(name, "_", " ") %>% str_to_title())
```

Cost burden & severe cost burden by neighborhood only

```{r}
hoods <- prof_df %>% 
  select(name, per_units_cost50) %>%
  slice(1:19) %>%
  setNames(c("name", "severe_burden"))

write_csv(hoods, "cost_burden_neighborhoods.csv")
```

```{r}
tenure <- prof_df %>%
  select(name, per_owned_cost50, per_rented_cost50) %>%
  slice(20:22) %>%
  setNames(c("name", "owner", "renter")) %>%
  gather(key = "tenure", value = "severe_burden", -name)

write_csv(tenure, "cost_burden_tenure.csv")
```

